name: Release Workflow

on:
  release:
    types: [published]

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.1"
          extensions: mbstring, xml
          coverage: none

      - name: Install dependencies
        run: composer install --no-dev --prefer-dist

      - name: Read version from config
        id: read-version
        run: |
          version=$(grep 'version' ./config/module.ini | cut -d '=' -f2 | tr -d ' "' | tr -d "\r")
          echo "Version: $version"
          echo "::set-output name=version::$version"

      - name: Prepare release
        run: |
          version=${{ steps.read-version.outputs.version }}
          name=YourPackageName # この行を動的に設定するか、スクリプトで取得するように変更してください。
          echo "Preparing release for $name version $version"
          rsync -ahv . "./$name" --exclude '.*' --exclude '*.sh' --exclude '/vendor'
          zip -r "./$name-$version.zip" "./$name"
          rm -rf "./$name"

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./${{ env.name }}-${{ steps.read-version.outputs.version }}.zip
          asset_name: $name-$version.zip
          asset_content_type: application/zip
